apiVersion: v1
kind: Template
metadata:
  name: router-metrics-template
  annotations:
    description: "Template for creating router metrics"
    iconClass: "icon-shadowman"
    tags: "router"
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: router-metrics
  spec:
    containers:
    - image: openshift/openshift-router-monitor
      name: router-metrics
      ports:
      - containerPort: 8000
        protocol: TCP
- kind: "Service"
  apiVersion: v1
  metadata:
    name: "router-metrics-service"
  annotations:
    description: "Exposes the router metrics pod"
  spec:
    ports:
      - name: "router-metrics-service"
        port: 8000
        targetPort: 8000
    selector:
      app: "router-metrics"
labels:
  app: router-metrics

